### ISSUE TITLE
Support larger buffer size for child_process

### ISSUE THREAD

**Issue by skyscribe** [domharrington/node-gitlog#16]
When traversing a repository with long history, the `child_process` would report error as 
`[Error: stdout maxBuffer exceeded.]`, can you pass a option so larger buffer size can be set as well?

**Comment by domharrington** [comment]
Would you mind manually adding and incrementing the [maxBuffer option](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) to this line: https://github.com/domharrington/node-gitlog/blob/2873f9cf609d9f11f7ac958e886fcd584e88391d/index.js#L89 and let me know how much to increase it by. Happy to do it if you tell me a suitable value for your use case.

Should be able to add it by changing that line to:

```js
exec(command, { maxBuffer: 400*1024 }, function(err, stdout, stderr) {
```

**Comment by domharrington** [comment]
A better approach to this would be to use https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options instead of `child_process.exec`. I dont believe this has the same problems because it does not need to buffer up the stream's output.

**Comment by atmd83** [comment]
Have made some changed to a fork using spawn instead of exec
[https://github.com/atmd83/node-gitlog/blob/master/index.js](https://github.com/atmd83/node-gitlog/blob/master/index.js)

**Comment by skyscribe** [comment]
I didn't get a chance to try updated version - I finally wrote an awk script to parse the log, performance was better than gitlog (I have a repository with 3 years' data to analyze).

I think this issue can be closed anyway, thanks all.
