### ISSUE TITLE
stdout maxBuffer exceeded when run on large projects

### ISSUE THREAD

**Issue by JamieMason** [domharrington/node-gitlog#19]
When running on a large git log, the following happens.

```
Error: stdout maxBuffer exceeded.
    at Socket.<anonymous> (child_process.js:244:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

A quick fix can be found by changing [index.js:89](https://github.com/domharrington/node-gitlog/blob/4b7ba82b52aeb198446dd0d8d2ec58b50f146e33/index.js#L89) from

```js
exec(command, function(err, stdout, stderr) {
```

to

```js
exec(command, { maxBuffer: Infinity }, function(err, stdout, stderr) {
```

or by using child_process.spawn instead.

Hope this helps, thanks!

**Comment by domharrington** [comment]
Thanks for reporting. This has already been raised here: https://github.com/domharrington/node-gitlog/issues/16. Happy to accept a pull request with either approach!

**Comment by domharrington** [comment]
This can now be done via the `execOptions` option: https://github.com/domharrington/node-gitlog#execoptions
