### ISSUE TITLE
when the author name contains an email it fails

### ISSUE THREAD

**Issue by joaomilho** [domharrington/node-gitlog#27]
e.g. Running `git log -p -1`:

```
commit 4849d0b60197662970d35d4bf4e78466c8e7a368
Merge: 5b55a8a f4db380
Author: Some Name <some@email.in>
Date:   Sun Jan 22 14:29:24 2017 +0200

    Merge with master
```

Running this lib in the same repo with `number: 1`:

```
[ { status: [],
    files: [],
    abbrevHash: '4849d0b',
    hash: '4849d0b60197662970d35d4bf4e78466c8e7a368',
    subject: 'Merge with master',
    authorName: 'Some Name@end@\n' } ]
```

**Comment by domharrington** [comment]
Thanks for reporting this issue. Would you mind submitting a failing test case as a pull request? What OS are you using? What version of git?

**Comment by metaodi** [comment]
This is actually the same issue as https://github.com/domharrington/node-gitlog/issues/28, the problem is with the merge commit, not with the email address in the author name.
