### ISSUE TITLE
@end@ is sometimes appended to the authorDate field

### ISSUE THREAD

**Issue by metaodi** [domharrington/node-gitlog#28]
I just tracked down a weird bug in my code, where I tried to convert the authorDate of a commit to a date object, but I kept getting "Invalid date" error messages. It turns out, sometimes node-gitlog appends `@end@` to the authorDate field. This does definitely not always happen and I could not yet find the logic behind (but I didn't yet spend too much time on it), though I thought I let you know.

For now I fixed this on my side using this line:

```javascript
commit.authorDate = commit.authorDate.replace('@end@', '');
```

But of course it would be nice to have this fixed in this library.

**Comment by posidron** [comment]
Did run into the same issue. It seems to happen when no 'files' and hence no 'status' fields are available which occurs during "Merge commits", then no '\n\n' is present and the split() part fails and keeps the '@end@' separator. https://github.com/domharrington/node-gitlog/blob/master/index.js#L145

**Comment by domharrington** [comment]
Hey @posidron would you mind writing a failing test case for this? Or submitting a pull request?

**Comment by metaodi** [comment]
@domharrington @posidron now that I know what exactly the issue is, I'm happy to submit a PR, I started by creating a failing test: https://github.com/domharrington/node-gitlog/pull/32

**Comment by posidron** [comment]
Locally I did replace https://github.com/domharrington/node-gitlog/blob/master/index.js#L145 with:

```const parts = commit.split(commit.includes('\n\n') ? '@end@\n\n' : '@end@')```
