### ISSUE TITLE
Body contains subject as well: Should use %b instead of %B

### ISSUE THREAD

**Issue by Gilwyad** [domharrington/node-gitlog#29]
commit.body contains both the subject and the body which is quite annoying. Changing %B to %b fixes that in index.js in the fields definition.

Also it would be good to mention in the readme that git version 1.7.1 does not expand the %B placeholder due to a bug so commit.body will simply be %B.

**Comment by domharrington** [comment]
Can you send a pull request for this change?

**Comment by domharrington** [comment]
Fixed in #30. Thanks
