### ISSUE TITLE
-m switch

### ISSUE THREAD

**Issue by monsterlane** [domharrington/node-gitlog#40]
Without the -m switch `git log` doesn't show files changed in a merge commit. The files array will be empty without this.

**Comment by domharrington** [comment]
I've not used this module in a while. Is this a recent change in git?

**Comment by monsterlane** [comment]
No apparently it's existed for some time and is undocumented on their Wiki. It's referenced in one of their examples. I found it on StackOverflow in a related topic.

**Comment by domharrington** [comment]
Can you show me some example code where this is a problem?

**Comment by monsterlane** [comment]
Merge a PR into a branch and have it log the last 10 commits. On each iteration output the subject and length of the files array. The files array will be length 0 with all the merge commits. Change this in the plugin;

`  // Start constructing command
  var command = 'git log -m '`

Run it again and you'll see the files in each merge commit.

**Comment by domharrington** [comment]
Are there any repercussions to always adding `-m`? Can you submit a PR with a test demonstrating the issue?

**Comment by monsterlane** [comment]
As far as I can tell no; using `-m` just includes more information on merge commits and others are unaffected. We've moved to Bitbucket so I can't send you a PR off my modified branch. A PR by itself probably won't do any good as the only way to simulate it is by having a merged PR in your history. If you want to test it you can use the version I published to NPM: https://www.npmjs.com/package/gitlogplus

**Comment by monsterlane** [comment]
-m
This flag makes the merge commits show the full diff like regular commits; for each merge parent, a separate log entry and diff is generated. An exception is that only diff against the first parent is shown when --first-parent option is given; in that case, the output represents the changes the merge brought into the then-current branch.

https://linux.die.net/man/1/git-log

After some more testing it appears this is the right command;

`var command = 'git log -m --first-parent '`

Without `--first-parent` you see multiple entries for a hash which probably isn't what you want to see. All we want is the files changed to the given branch by the merge which using that option provides.

**Comment by monsterlane** [comment]
Hopefully this won't be super confusing but this is what I'm seeing. Say we have four branches:

master
branch-a (branched off master)
branch-b (branched off master)
release

Dev B makes some changes in branch-b. While they are doing this, Dev A merges branch-a into master. Dev B now merges master into branch-b to bring it up to date. Dev B now merges branch-b into release. We run this plugin on the release branch to pull it's history.

Without `-m` we see no files changed for the merge commits.
With `-m` we see two merge with the same hash, one being the actual files the dev changed the other being the merge files changed from Dev A's branch-a -> master merge.
With `-m --first-parent` we see a single hash with only the files changed by merging branch-b into release.

**Comment by domharrington** [comment]
Thanks for your detailed analysis of the problem. Would you mind writing an automated test for this case?

The tests are here: https://github.com/domharrington/node-gitlog/blob/master/test/gitlog.test.js
The fixtures are here: https://github.com/domharrington/node-gitlog/blob/master/test/create-repo.sh

I'm a little unsure if this is the right thing to do, so proofing that it doesnt cause any regression would be great.

**Comment by hipstersmoothie** [comment]
@domharrington I have found I need this flag too. Instead of making it the default how about I just add it as a config option?
