### ISSUE TITLE
No support for line range 

### ISSUE THREAD

**Issue by SalmonMode** [domharrington/node-gitlog#60]
I'd like to be able to look up the log history for a specific line of a file, or a range of lines in a file

**Comment by hipstersmoothie** [comment]
Is this something that `git log` supports? Feel free to make a PR adding this capability

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v4.0.2`](https://github.com/domharrington/node-gitlog/releases/tag/v4.0.2) :rocket:
